import { Router } from 'express';
import healthCheck from './health-check.js';
import integratedAiRouter from './integrated-ai.js';
import marketData from './market-data.js';
import marketNews from './market-news.js';
import quotes from './quotes.js';
import candles from './candles.js';
import indicator from './indicator.js';
import heatmap from './heatmap.js';
import economicCalendar from './economic-calendar.js';
import authSendEmail, { authSendEmailStatus } from './auth-send-email.js';
import { intraday, daily, weekly, monthly } from './market-series.js';
import walletRouter from './wallet.js';
import tbcRouter from './tbc.js';
import challengesRouter from './challenges.js';
import backtestRouter from './backtest.js';
import ecosystemRouter from './ecosystem.js';
import marketRouter from './market.js';
import paperRouter from './paper.js';
import paddleRouter from './paddle.js';
import stripeRouter from './stripe.js';
import affiliateRouter from './affiliate.js';
import securityRouter from './security.js';
import supportRouter from './support.js';
import adsRouter from './ads.js';
import adminRouter from './admin.js';
import academyRouter from './academy.js';
import digestRouter from './digest.js';
import dunsRouter from './duns.js';
import companyRouter from './company.js';
import jobsRouter from './jobs.js';
import brokersRouter from './brokers.js';
import terminalRouter from './terminal.js';

const router = Router();

export default () => {
    router.get('/health', healthCheck);
    router.post('/auth/send-email', authSendEmail);
    router.get('/auth/send-email/status', authSendEmailStatus);
    router.use('/integrated-ai', integratedAiRouter);
    router.get('/market-data', marketData);
    router.get('/market-news', marketNews);
    router.get('/quotes', quotes);
    router.get('/candles', candles);
    router.get('/indicator', indicator);
    router.get('/heatmap', heatmap);
    router.get('/economic-calendar', economicCalendar);
    router.get('/intraday', intraday);
    router.get('/daily', daily);
    router.get('/weekly', weekly);
    router.get('/monthly', monthly);
    router.use('/wallet', walletRouter);
    router.use('/tbc', tbcRouter);
    router.use('/challenges', challengesRouter);
    router.use('/backtest', backtestRouter);
    router.use('/', ecosystemRouter);
    router.use('/market', marketRouter);
    router.use('/paper', paperRouter);
    router.use('/paddle', paddleRouter);
    router.use('/stripe', stripeRouter);
    router.use('/affiliate', affiliateRouter);
    router.use('/security', securityRouter);
    router.use('/support', supportRouter);
    router.use('/ads', adsRouter);
    router.use('/admin', adminRouter);
    router.use('/admin/digest', digestRouter);
    router.use('/academy', academyRouter);
    router.use('/duns', dunsRouter);
    router.use('/company', companyRouter);
    router.use('/jobs', jobsRouter);
    router.use('/brokers', brokersRouter);
    router.use('/terminal', terminalRouter);

    return router;
};
