// Tradable symbols grouped by market, used across the charting surfaces
// (Terminal, LiveChart, ChartPanel, Watchlists, Indicators, Alerts, Signals).
// Mirrors the API heatmap/quotes/candles registries so every pair is
// available in every feature. Crypto resolves live via Binance, US stocks
// via Finnhub when configured, everything else via Alpha Vantage/synthetic.
export const SYMBOL_GROUPS = [
  {
    label: 'Crypto',
    symbols: [
      { symbol: 'BTCUSD', name: 'Bitcoin' }, { symbol: 'ETHUSD', name: 'Ethereum' },
      { symbol: 'SOLUSD', name: 'Solana' }, { symbol: 'BNBUSD', name: 'BNB' },
      { symbol: 'XRPUSD', name: 'XRP' }, { symbol: 'ADAUSD', name: 'Cardano' },
      { symbol: 'DOGEUSD', name: 'Dogecoin' }, { symbol: 'AVAXUSD', name: 'Avalanche' },
      { symbol: 'DOTUSD', name: 'Polkadot' }, { symbol: 'LINKUSD', name: 'Chainlink' },
      { symbol: 'MATICUSD', name: 'Polygon' }, { symbol: 'LTCUSD', name: 'Litecoin' },
      { symbol: 'TRXUSD', name: 'TRON' }, { symbol: 'ATOMUSD', name: 'Cosmos' },
      { symbol: 'UNIUSD', name: 'Uniswap' }, { symbol: 'NEARUSD', name: 'NEAR Protocol' },
      { symbol: 'APTUSD', name: 'Aptos' }, { symbol: 'FILUSD', name: 'Filecoin' },
      { symbol: 'ICPUSD', name: 'Internet Computer' }, { symbol: 'ETCUSD', name: 'Ethereum Classic' },
      { symbol: 'ARBUSD', name: 'Arbitrum' }, { symbol: 'OPUSD', name: 'Optimism' },
      { symbol: 'SUIUSD', name: 'Sui' }, { symbol: 'SEIUSD', name: 'Sei' },
      { symbol: 'TIAUSD', name: 'Celestia' }, { symbol: 'ONDOUSD', name: 'Ondo' },
      { symbol: 'INJUSD', name: 'Injective' }, { symbol: 'STXUSD', name: 'Stacks' },
      { symbol: 'IMXUSD', name: 'Immutable' }, { symbol: 'HBARUSD', name: 'Hedera' },
      { symbol: 'VETUSD', name: 'VeChain' }, { symbol: 'ALGOUSD', name: 'Algorand' },
      { symbol: 'QNTUSD', name: 'Quant' }, { symbol: 'GRTUSD', name: 'The Graph' },
      { symbol: 'THETAUSD', name: 'Theta' }, { symbol: 'EGLDUSD', name: 'MultiversX' },
      { symbol: 'RUNEUSD', name: 'THORChain' }, { symbol: 'KASUSD', name: 'Kaspa' },
      { symbol: 'FETUSD', name: 'Fetch.ai' }, { symbol: 'RENDERUSD', name: 'Render' },
      { symbol: 'GALAUSD', name: 'Gala' }, { symbol: 'SANDUSD', name: 'Sandbox' },
      { symbol: 'MANAUSD', name: 'Decentraland' }, { symbol: 'AXSUSD', name: 'Axie Infinity' },
      { symbol: 'AAVEUSD', name: 'Aave' }, { symbol: 'MKRUSD', name: 'Maker' },
      { symbol: 'LDOUSD', name: 'Lido' }, { symbol: 'ENAUSD', name: 'Ethena' },
      { symbol: 'PENDLEUSD', name: 'Pendle' }, { symbol: 'JUPUSD', name: 'Jupiter' },
      { symbol: 'PYTHUSD', name: 'Pyth' }, { symbol: 'WLDUSD', name: 'Worldcoin' },
      { symbol: 'PEPEUSD', name: 'Pepe' }, { symbol: 'SHIBUSD', name: 'Shiba Inu' },
      { symbol: 'BONKUSD', name: 'Bonk' }, { symbol: 'WIFUSD', name: 'dogwifhat' },
      { symbol: 'FLOKIUSD', name: 'Floki' }, { symbol: 'JASMYUSD', name: 'JasmyCoin' },
      { symbol: 'ORDIUSD', name: 'Ordinals' }, { symbol: 'BLURUSD', name: 'Blur' },
    ],
  },
  {
    label: 'Forex',
    symbols: [
      { symbol: 'EURUSD', name: 'Euro / USD' }, { symbol: 'GBPUSD', name: 'GBP / USD' },
      { symbol: 'USDJPY', name: 'USD / JPY' }, { symbol: 'USDCHF', name: 'USD / CHF' },
      { symbol: 'AUDUSD', name: 'AUD / USD' }, { symbol: 'USDCAD', name: 'USD / CAD' },
      { symbol: 'NZDUSD', name: 'NZD / USD' }, { symbol: 'EURGBP', name: 'Euro / Pound' },
      { symbol: 'EURJPY', name: 'Euro / Yen' }, { symbol: 'GBPJPY', name: 'GBP / JPY' },
      { symbol: 'AUDJPY', name: 'AUD / Yen' }, { symbol: 'CHFJPY', name: 'Swiss / Yen' },
      { symbol: 'EURCHF', name: 'Euro / Swiss' }, { symbol: 'EURAUD', name: 'Euro / Aussie' },
      { symbol: 'EURNZD', name: 'Euro / Kiwi' }, { symbol: 'EURCAD', name: 'Euro / Canada' },
      { symbol: 'EURSEK', name: 'Euro / Sweden' }, { symbol: 'EURNOK', name: 'Euro / Norway' },
      { symbol: 'EURZAR', name: 'Euro / Rand' }, { symbol: 'EURMXN', name: 'Euro / Peso' },
      { symbol: 'GBPAUD', name: 'Pound / Aussie' }, { symbol: 'GBPCAD', name: 'Pound / Canada' },
      { symbol: 'GBPNZD', name: 'Pound / Kiwi' }, { symbol: 'GBPCHF', name: 'Pound / Swiss' },
      { symbol: 'GBPZAR', name: 'Pound / Rand' }, { symbol: 'AUDCAD', name: 'Aussie / Canada' },
      { symbol: 'AUDNZD', name: 'Aussie / Kiwi' }, { symbol: 'AUDCHF', name: 'Aussie / Swiss' },
      { symbol: 'NZDCAD', name: 'Kiwi / Canada' }, { symbol: 'NZDCHF', name: 'Kiwi / Swiss' },
      { symbol: 'NZDJPY', name: 'Kiwi / Yen' }, { symbol: 'CADJPY', name: 'Canada / Yen' },
      { symbol: 'CADCHF', name: 'Canada / Swiss' }, { symbol: 'USDSGD', name: 'USD / Singapore' },
      { symbol: 'USDHKD', name: 'USD / HK Dollar' }, { symbol: 'USDMXN', name: 'USD / Peso' },
      { symbol: 'USDZAR', name: 'USD / Rand' }, { symbol: 'USDTRY', name: 'USD / Lira' },
      { symbol: 'USDSEK', name: 'USD / Sweden' }, { symbol: 'USDNOK', name: 'USD / Norway' },
    ],
  },
  {
    label: 'Commodities',
    symbols: [
      { symbol: 'XAUUSD', name: 'Gold' }, { symbol: 'XAGUSD', name: 'Silver' },
      { symbol: 'WTIUSD', name: 'Crude Oil WTI' }, { symbol: 'BRENT', name: 'Brent Oil' },
      { symbol: 'NATGAS', name: 'Natural Gas' }, { symbol: 'COPPER', name: 'Copper' },
      { symbol: 'PLATINUM', name: 'Platinum' }, { symbol: 'PALLADIUM', name: 'Palladium' },
      { symbol: 'WHEAT', name: 'Wheat' }, { symbol: 'CORN', name: 'Corn' },
      { symbol: 'SOYUSD', name: 'Soybeans' }, { symbol: 'SUGARUSD', name: 'Sugar' },
      { symbol: 'COFFEEUSD', name: 'Coffee' }, { symbol: 'COCOAUSD', name: 'Cocoa' },
      { symbol: 'COTTONUSD', name: 'Cotton' }, { symbol: 'ALUMUSD', name: 'Aluminum' },
      { symbol: 'ZINCUSD', name: 'Zinc' }, { symbol: 'NICKELUSD', name: 'Nickel' },
      { symbol: 'GASOLINEUSD', name: 'Gasoline' }, { symbol: 'HEATOILUSD', name: 'Heating Oil' },
    ],
  },
  {
    label: 'Indices',
    symbols: [
      { symbol: 'NQ', name: 'Nasdaq 100' }, { symbol: 'ES', name: 'S&P 500' },
      { symbol: 'DJI', name: 'Dow Jones' }, { symbol: 'SPX', name: 'S&P 500 Index' },
      { symbol: 'RUT', name: 'Russell 2000' }, { symbol: 'VIX', name: 'Volatility Index' },
    ],
  },
  {
    label: 'Sectors',
    symbols: [
      { symbol: 'XLK', name: 'Technology' }, { symbol: 'XLF', name: 'Finance' },
      { symbol: 'XLV', name: 'Healthcare' }, { symbol: 'XLE', name: 'Energy' },
      { symbol: 'XLY', name: 'Consumer' }, { symbol: 'XLI', name: 'Industrials' },
      { symbol: 'XLB', name: 'Materials' }, { symbol: 'XLU', name: 'Utilities' },
      { symbol: 'XLRE', name: 'Real Estate' }, { symbol: 'XLC', name: 'Communication' },
      { symbol: 'XBI', name: 'Biotech' }, { symbol: 'XOP', name: 'Oil & Gas' },
      { symbol: 'XHB', name: 'Homebuilders' }, { symbol: 'XRT', name: 'Retail' },
      { symbol: 'KRE', name: 'Regional Banks' }, { symbol: 'SMH', name: 'Semiconductors' },
      { symbol: 'XME', name: 'Metals & Mining' }, { symbol: 'XAR', name: 'Aerospace & Defense' },
      { symbol: 'TAN', name: 'Solar' }, { symbol: 'JETS', name: 'Airlines' },
    ],
  },
  {
    label: 'Stocks',
    symbols: [
      { symbol: 'AAPL', name: 'Apple' }, { symbol: 'MSFT', name: 'Microsoft' },
      { symbol: 'GOOGL', name: 'Alphabet' }, { symbol: 'AMZN', name: 'Amazon' },
      { symbol: 'TSLA', name: 'Tesla' }, { symbol: 'META', name: 'Meta' },
      { symbol: 'NVDA', name: 'NVIDIA' }, { symbol: 'JPM', name: 'JPMorgan' },
      { symbol: 'V', name: 'Visa' }, { symbol: 'WMT', name: 'Walmart' },
      { symbol: 'JNJ', name: 'J&J' }, { symbol: 'PG', name: 'P&G' },
      { symbol: 'MA', name: 'Mastercard' }, { symbol: 'HD', name: 'Home Depot' },
      { symbol: 'XOM', name: 'Exxon' }, { symbol: 'BAC', name: 'Bank of America' },
      { symbol: 'KO', name: 'Coca-Cola' }, { symbol: 'PEP', name: 'PepsiCo' },
      { symbol: 'NFLX', name: 'Netflix' }, { symbol: 'ADBE', name: 'Adobe' },
      { symbol: 'CRM', name: 'Salesforce' }, { symbol: 'INTC', name: 'Intel' },
      { symbol: 'AMD', name: 'AMD' }, { symbol: 'DIS', name: 'Disney' },
      { symbol: 'ORCL', name: 'Oracle' }, { symbol: 'CSCO', name: 'Cisco' },
      { symbol: 'PFE', name: 'Pfizer' }, { symbol: 'NKE', name: 'Nike' },
      { symbol: 'MCD', name: "McDonald's" }, { symbol: 'T', name: 'AT&T' },
      { symbol: 'VZ', name: 'Verizon' }, { symbol: 'ABBV', name: 'AbbVie' },
      { symbol: 'CVX', name: 'Chevron' }, { symbol: 'WFC', name: 'Wells Fargo' },
      { symbol: 'MRK', name: 'Merck' }, { symbol: 'COST', name: 'Costco' },
      { symbol: 'TMO', name: 'Thermo' }, { symbol: 'ACN', name: 'Accenture' },
      { symbol: 'DHR', name: 'Danaher' }, { symbol: 'LIN', name: 'Linde' },
      { symbol: 'TXN', name: 'Texas Inst' }, { symbol: 'QCOM', name: 'Qualcomm' },
      { symbol: 'HON', name: 'Honeywell' }, { symbol: 'UPS', name: 'UPS' },
      { symbol: 'PM', name: 'Philip Morris' }, { symbol: 'IBM', name: 'IBM' },
      { symbol: 'GE', name: 'GE' }, { symbol: 'CAT', name: 'Caterpillar' },
      { symbol: 'BA', name: 'Boeing' }, { symbol: 'GS', name: 'Goldman Sachs' },
      { symbol: 'AVGO', name: 'Broadcom' }, { symbol: 'LLY', name: 'Eli Lilly' },
      { symbol: 'UNH', name: 'UnitedHealth' }, { symbol: 'AMAT', name: 'Applied Materials' },
      { symbol: 'MU', name: 'Micron' }, { symbol: 'LRCX', name: 'Lam Research' },
      { symbol: 'KLAC', name: 'KLA' }, { symbol: 'ADI', name: 'Analog Devices' },
      { symbol: 'PANW', name: 'Palo Alto' }, { symbol: 'NOW', name: 'ServiceNow' },
      { symbol: 'INTU', name: 'Intuit' }, { symbol: 'AMGN', name: 'Amgen' },
      { symbol: 'GILD', name: 'Gilead' }, { symbol: 'ISRG', name: 'Intuitive Surgical' },
      { symbol: 'SYK', name: 'Stryker' }, { symbol: 'BSX', name: 'Boston Scientific' },
      { symbol: 'SHW', name: 'Sherwin-Williams' }, { symbol: 'APD', name: 'Air Products' },
      { symbol: 'NEE', name: 'NextEra' }, { symbol: 'DUK', name: 'Duke Energy' },
      { symbol: 'AMT', name: 'American Tower' }, { symbol: 'PLD', name: 'Prologis' },
      { symbol: 'EQIX', name: 'Equinix' }, { symbol: 'MDLZ', name: 'Mondelez' },
      { symbol: 'CL', name: 'Colgate' }, { symbol: 'BKNG', name: 'Booking' },
      { symbol: 'RCL', name: 'Royal Caribbean' }, { symbol: 'UAL', name: 'United Airlines' },
      { symbol: 'DAL', name: 'Delta' }, { symbol: 'FDX', name: 'FedEx' },
      { symbol: 'UNP', name: 'Union Pacific' }, { symbol: 'CSX', name: 'CSX' },
      { symbol: 'MMM', name: '3M' }, { symbol: 'LOW', name: "Lowe's" },
      { symbol: 'TJX', name: 'TJX' }, { symbol: 'F', name: 'Ford' },
      { symbol: 'GM', name: 'General Motors' }, { symbol: 'MO', name: 'Altria' },
      { symbol: 'ADP', name: 'ADP' }, { symbol: 'MSI', name: 'Motorola' },
      { symbol: 'NOC', name: 'Northrop' }, { symbol: 'LMT', name: 'Lockheed' },
      { symbol: 'RTX', name: 'RTX' }, { symbol: 'D', name: 'Dominion' },
      { symbol: 'EXC', name: 'Exelon' }, { symbol: 'WM', name: 'Waste Mgmt' },
      { symbol: 'EMR', name: 'Emerson' }, { symbol: 'ETN', name: 'Eaton' },
      { symbol: 'AFL', name: 'Aflac' }, { symbol: 'PRU', name: 'Prudential' },
    ],
  },
];

export const ALL_SYMBOLS = SYMBOL_GROUPS.flatMap((g) => g.symbols);
